### ISSUE TITLE
[BUG] Dissmissed responses are (but should not be) counted in the summary graph

### ISSUE THREAD

**Issue by MaxWohlers** [formbricks/formbricks#2908]
### Issue Summary

Asking for rating or other question in a live-intercept survey, I have the possibility to turn off the 'required' field, meaning that users do not have to answer the question. 
While it is of course interesting to see how many users dismissed a certain question, this number/proportion should not be counted within the actual summary graph in the overview. I am only interested in the actual proportions of the responses. 

<img width="1158" alt="Bildschirmfoto 2024-07-17 um 14 00 04" src="https://github.com/user-attachments/assets/6c6450f1-c76a-41cb-9455-1d5e5de39eb1">

### Steps to Reproduce

1. Turn off 'required' for rating question
2. Go into summary
4. See dismissed response proportions being counted to the actual graph

### Expected behavior

Dismissed responses (and proportions) **should not** be added to the summary graph. 

The amount/proportion of dismissed responses can of course be mentioned next/under the graph.

### Environment

- [ ] Formbricks Cloud (app.formbricks.com)
- [X] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS:
- Node:
- npm:
```

**Comment by KrishDave1** [comment]
Hi @MaxWohlers , I was not able to reproduce the issue.Could you help me reproduce the bug?Also adding on the bug, I found if user does not select anything, there is no message displayed to user saying "no options selected" or something like that.

Attaching the image below,
![image](https://github.com/user-attachments/assets/8cd4c1a2-7e06-4fae-ac41-7e090d329e13)

**Comment by KrishDave1** [comment]
Hi @MaxWohlers , I noticed the same problem on the live application.However, when I set it up on my local machine the issue is already resolved.Could you help to reproduce the issue?

**Comment by MaxWohlers** [comment]
Here you go! :)
https://github.com/user-attachments/assets/cd1236d1-f0b9-4215-8000-a4ddf7ecf2d0

**Comment by mattinannt** [comment]
@MaxWohlers Thanks for bringing this up. This makes sense. We will update the summary view so that only the actual responses to that question are counted and used to calculate the percentage. We will still show the "Dismissed" count at the bottom (but without the percentage and progress bar).

**Comment by KrishDave1** [comment]
Could you please assign this to me
